version: '3'

services:
  app:
    command: bash -c 'npm ci && npm run dev'
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"

  caddy:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
