version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: kochetov/devops-for-programmers-project-74
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
    command: npm test
    depends_on: [ db ]

  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_HOST: ${DATABASE_HOST}
volumes:
    pgdata:
